# ruff: noqa: F401

import pytest

from tests.pma_routes_support import (
    test_build_pma_routes_does_not_construct_async_primitives_on_route_build,
    test_build_pma_routes_registers_unique_method_path_pairs,
    test_execute_opencode_records_completion_only_messages_in_timeline,
    test_pma_active_clears_on_prompt_build_error,
    test_pma_active_updates_during_running_turn,
    test_pma_agents_endpoint,
    test_pma_agents_endpoint_advertises_hermes_active_thread_discovery,
    test_pma_agents_endpoint_prefers_hermes_default_profile_over_global_default,
    test_pma_agents_endpoint_surfaces_hermes_optional_controls_and_commands,
    test_pma_chat_applies_model_reasoning_defaults,
    test_pma_chat_codex_ignores_global_profile_default_when_agent_has_no_profiles,
    test_pma_chat_codex_retries_with_fresh_conversation_after_stale_resume,
    test_pma_chat_github_injection_uses_raw_user_message,
    test_pma_chat_hermes_profile_uses_profile_scoped_registry_binding,
    test_pma_chat_hermes_reuses_agent_scoped_registry_binding,
    test_pma_chat_idempotency_key_uses_full_message,
    test_pma_chat_persists_transcript_and_history_entry,
    test_pma_chat_register_turn_failure_is_best_effort,
    test_pma_chat_rejects_oversize_message,
    test_pma_chat_requires_message,
    test_pma_chat_response_omits_legacy_delivery_fields,
    test_pma_chat_returns_completed_queue_result_when_future_is_registered_late,
    test_pma_chat_submits_through_surface_orchestration_ingress,
    test_pma_compact_creates_artifact,
    test_pma_history_detail_includes_turn_timeline,
    test_pma_interrupt_route_interrupts_running_hermes_turn,
    test_pma_interrupt_route_interrupts_running_turn,
    test_pma_managed_thread_status_and_tail_use_orchestration_service,
    test_pma_new_creates_artifact,
    test_pma_new_forks_current_hermes_thread_when_runtime_supports_it,
    test_pma_queue_endpoints_report_lane_items,
    test_pma_reset_creates_artifact,
    test_pma_routes_disabled_by_config,
    test_pma_routes_enabled_by_default,
    test_pma_second_lane_item_does_not_clobber_active_turn,
    test_pma_stop_creates_artifact,
    test_pma_target_endpoints_are_removed,
    test_pma_thread_reset_clears_registry,
    test_pma_thread_status_includes_queued_turns,
    test_pma_turn_events_stream_codex_respects_resume_cursor,
    test_pma_turn_events_stream_hermes_uses_runtime_harness,
    test_pma_turn_events_stream_opencode_returns_empty_stream_without_pending_turn,
    test_pma_wakeup_failure_publishes_failure_summary,
    test_pma_wakeup_publish_retries_transient_telegram_enqueue_failure,
    test_pma_wakeup_turn_publishes_to_discord_and_telegram_outboxes,
    test_pma_wakeup_turn_publishes_using_prev_workspace_repo_context,
)

pytestmark = pytest.mark.slow
