# ruff: noqa: F401

import pytest

pytestmark = pytest.mark.slow

from tests.pma_context_support import (
    test_build_hub_snapshot_auto_dismisses_unrecoverable_stopped_run_after_grace,
    test_build_hub_snapshot_clears_stale_exit_code_when_last_run_id_is_rewritten,
    test_build_hub_snapshot_demotes_stale_paused_dispatch_when_no_tickets_remain,
    test_build_hub_snapshot_failed_run_queue_item_recommends_archive_with_repo,
    test_build_hub_snapshot_filters_dismissed_stopped_run_from_inbox_and_queue,
    test_build_hub_snapshot_ignores_pma_self_thread_hung_noise,
    test_build_hub_snapshot_includes_action_queue_with_supersession,
    test_build_hub_snapshot_includes_agent_workspaces_section,
    test_build_hub_snapshot_includes_automation_summary,
    test_build_hub_snapshot_includes_effective_destination,
    test_build_hub_snapshot_includes_pma_threads_section,
    test_build_hub_snapshot_includes_templates,
    test_build_hub_snapshot_keeps_failed_worker_dead_legacy_run_visible_during_auto_dismiss_grace_when_no_tickets_remain,
    test_build_hub_snapshot_keeps_failed_worker_dead_run_visible_during_auto_dismiss_grace_when_no_tickets_remain,
    test_build_hub_snapshot_keeps_stopped_run_visible_when_no_tickets_remain,
    test_build_hub_snapshot_marks_stale_start_new_flow_recommendations,
    test_build_hub_snapshot_prefers_status_change_time_for_thread_freshness,
    test_build_hub_snapshot_repo_entries_include_canonical_state_v1,
    test_build_hub_snapshot_surfaces_unreadable_latest_dispatch,
    test_format_pma_prompt_includes_filebox_paths,
    test_render_hub_snapshot_caps_pma_file_action_summaries,
    test_render_hub_snapshot_distinguishes_run_dispatch_vs_pma_files,
    test_render_hub_snapshot_empty_both,
    test_render_hub_snapshot_includes_all_next_action_types,
    test_render_hub_snapshot_includes_repo_destination,
    test_render_hub_snapshot_marks_stale_pma_files_as_review_only,
    test_render_hub_snapshot_marks_stale_sections_with_warning,
    test_render_hub_snapshot_pma_files_only,
)
