# ruff: noqa: F401

from tests.integrations.telegram.test_newt_workspace_commands import (
    test_newt_branch_name_includes_chat_identity,
    test_newt_dirty_worktree_reports_blockers_with_submodule_context,
    test_newt_infers_base_repo_from_legacy_wt_worktree_id,
    test_newt_infers_base_repo_from_worktree_id_when_missing_metadata,
    test_newt_prefers_longest_manifest_base_match_for_worktree_id,
    test_newt_runs_hub_setup_commands_for_workspace,
    test_newt_thread_fallback_and_workspace_state_reset,
)
from tests.telegram_pma_routing_support import (
    test_apply_compact_summary_preserves_pma_mode_for_replacement_thread,
    test_apply_compact_summary_uses_shared_lifecycle_before_topic_mirror_update,
    test_archive_uses_shared_fresh_start_and_resets_topic,
    test_archive_without_hub_root_does_not_substitute_workspace_root,
    test_help_text_mentions_pma_mode,
    test_mcp_lists_failure_message_on_app_server_response_error,
    test_pma_new_resets_managed_binding_when_runtime_threads_enabled,
    test_pma_new_resets_scoped_key_when_require_topics_enabled,
    test_pma_new_resets_session,
    test_pma_off_disables_mode,
    test_pma_on_enables_mode,
    test_pma_on_is_idempotent_when_already_enabled,
    test_pma_registry_key_matches_logical_hermes_profile,
    test_pma_reset_resets_scoped_key_when_require_topics_enabled,
    test_pma_resume_uses_hub_root,
    test_pma_status_reports_bound_workspace_when_disabled,
    test_pma_status_reports_disabled_mode,
    test_pma_targets_subcommand_uses_usage_text,
    test_pma_without_subcommand_reports_status,
    test_repo_managed_thread_turn_matches_pending_compact_seed_by_managed_thread_id,
    test_require_topics_uses_scoped_pma_registry_key,
    test_reset_telegram_thread_binding_archives_after_lost_backend_recovery,
    test_resolve_telegram_managed_thread_allows_missing_runtime_instance,
    test_resolve_telegram_managed_thread_keeps_requested_backend_thread_id_for_new_thread,
    test_resolve_telegram_managed_thread_rejects_rebind_when_runtime_missing,
    test_resume_opencode_missing_session_clears_stale_topic_state,
    test_resume_thread_by_id_rebinds_managed_thread_before_topic_mirror_update,
    test_sync_telegram_thread_binding_allows_missing_runtime_instance,
    test_sync_telegram_thread_binding_archives_after_lost_backend_recovery,
    test_sync_telegram_thread_binding_ignores_backend_id_in_pma_mode,
    test_sync_telegram_thread_binding_keeps_requested_backend_thread_id_for_replacement,
    test_sync_telegram_thread_binding_rejects_rebind_when_runtime_missing,
)
