# ruff: noqa: F401

import pytest
from tests.discord_message_turns_queue_notice_support import (
    test_orchestrated_turn_pma_queued_sends_fresh_progress_placeholder,
)
from tests.discord_message_turns_support import (
    test_build_attachment_filename_does_not_infer_audio_suffix_for_video,
    test_build_attachment_filename_uses_source_url_audio_suffix,
    test_build_message_session_key_is_registry_valid,
    test_build_message_session_key_pma_matches_logical_agent_profile,
    test_message_create_personal_bound_channel_runs_without_collaboration_policy,
    test_orchestrated_turn_begin_failure_deletes_progress_placeholder,
    test_orchestrated_turn_interrupt_send_acknowledges_when_progress_message_missing,
    test_orchestrated_turn_interrupt_send_falls_back_when_progress_ack_edit_fails,
    test_orchestrated_turn_interrupt_send_hands_off_progress_message,
    test_orchestrated_turn_interrupt_send_reuses_existing_progress_message,
    test_orchestrated_turn_placeholder_sent_before_runtime_begin,
    test_orchestrated_turn_queued_updates_placeholder_skips_finalize,
    test_orchestrated_turn_submission_timeout_deletes_progress_placeholder,
    test_resolve_discord_turn_policies_maps_safe_to_prompted_workspace_write,
    test_resolve_discord_turn_policies_prefers_binding_preset,
    test_resolve_discord_turn_policies_prefers_explicit_binding_values,
    test_run_managed_thread_turn_for_message_uses_binding_policies,
    test_sanitize_runtime_thread_result_error_maps_interrupted_to_surface_interrupted,
    test_sanitize_runtime_thread_result_error_maps_timeout_to_surface_timeout,
    test_sanitize_runtime_thread_result_error_preserves_sanitized_detail,
    test_sanitize_runtime_thread_result_error_returns_public_error_for_empty_detail,
    test_voice_service_for_workspace_caches_env_by_workspace,
    test_voice_service_for_workspace_uses_hub_config_path,
)

pytestmark = pytest.mark.slow
