from __future__ import annotations

import asyncio
import json
import logging
import sqlite3
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path

import pytest

from codex_autorunner.core.config import CONFIG_FILENAME, DEFAULT_HUB_CONFIG
from codex_autorunner.core.orchestration.sqlite import open_orchestration_sqlite
from codex_autorunner.core.pma_thread_store import PmaThreadStore
from codex_autorunner.core.pr_bindings import PrBindingStore
from codex_autorunner.core.publish_executor import (
    PublishExecutorRegistry,
    PublishOperationProcessor,
    TerminalPublishError,
    drain_pending_publish_operations,
)
from codex_autorunner.core.publish_journal import PublishJournalStore, PublishOperation
from codex_autorunner.core.publish_operation_executors import (
    build_enqueue_managed_turn_executor,
    build_notify_chat_executor,
)
from codex_autorunner.core.scm_events import ScmEventStore
from codex_autorunner.integrations.discord.state import DiscordStateStore
from codex_autorunner.integrations.github.publisher import (
    build_post_pr_comment_executor,
    build_react_pr_review_comment_executor,
)
from codex_autorunner.integrations.github.service import RepoInfo
from tests.conftest import write_test_config

_ALLOW_PR_COMMENT_POLICY = {
    "github": {"automation": {"policy": {"post_pr_comment": "allow"}}}
}
_ALLOW_REVIEW_COMMENT_REACTION_POLICY = {
    "github": {"automation": {"policy": {"react_pr_review_comment": "allow"}}}
}


def _parse_utc(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)


class _QueuedClock:
    def __init__(self, *timestamps: str) -> None:
        self._timestamps = [_parse_utc(value) for value in timestamps]
        self._index = 0

    def __call__(self) -> datetime:
        if not self._timestamps:
            raise AssertionError("clock requires at least one timestamp")
        index = min(self._index, len(self._timestamps) - 1)
        self._index += 1
        return self._timestamps[index]


def _attempt_rows(hub_root: Path, operation_id: str) -> list[dict[str, object]]:
    with open_orchestration_sqlite(hub_root) as conn:
        rows = conn.execute(
            """
            SELECT attempt_number, state, response_json, error_text, claimed_at, started_at, finished_at
              FROM orch_publish_attempts
             WHERE operation_id = ?
             ORDER BY attempt_number ASC
            """,
            (operation_id,),
        ).fetchall()
    return [dict(row) for row in rows]


def _publish_hub(tmp_path: Path) -> tuple[Path, Path, str]:
    hub_root = tmp_path / "hub"
    ca_dir = hub_root / ".codex-autorunner"
    ca_dir.mkdir(parents=True, exist_ok=True)
    (ca_dir / ".gitignore").write_text("*", encoding="utf-8")
    cfg = json.loads(json.dumps(DEFAULT_HUB_CONFIG))
    cfg["discord_bot"]["enabled"] = True
    cfg["telegram_bot"]["enabled"] = True
    write_test_config(hub_root / CONFIG_FILENAME, cfg)
    workspace_root = (hub_root / "worktrees" / "repo-publish").resolve()
    workspace_root.mkdir(parents=True, exist_ok=True)
    (ca_dir / "manifest.yml").write_text(
        "\n".join(
            [
                "# GENERATED by CAR - DO NOT EDIT",
                "version: 3",
                "repos:",
                "  - id: repo-publish",
                f"    path: {workspace_root.relative_to(hub_root).as_posix()}",
                "    enabled: true",
                "    auto_run: false",
                "    kind: base",
                "",
            ]
        ),
        encoding="utf-8",
    )
    (ca_dir / "hub_state.json").write_text(
        '{\n  "last_scan_at": null,\n  "repos": [],\n  "pinned_parent_repo_ids": []\n}\n',
        encoding="utf-8",
    )
    return hub_root, workspace_root, "repo-publish"


def _create_scm_enqueue_operation(
    *,
    journal: PublishJournalStore,
    thread_target_id: str,
    binding_id: str,
    repo_id: str,
    operation_key: str,
) -> PublishOperation:
    operation, _ = journal.create_operation(
        operation_key=operation_key,
        operation_kind="enqueue_managed_turn",
        payload={
            "thread_target_id": thread_target_id,
            "request": {
                "kind": "message",
                "message_text": "New PR review feedback arrived on acme/widgets#42.",
                "metadata": {
                    "scm": {
                        "binding_id": binding_id,
                        "event_id": "github:event-review-comment",
                        "provider": "github",
                        "repo_slug": "acme/widgets",
                        "repo_id": repo_id,
                        "pr_number": 42,
                    }
                },
            },
            "scm_reaction": {
                "binding_id": binding_id,
                "event_id": "github:event-review-comment",
                "provider": "github",
                "reaction_kind": "review_comment",
                "repo_slug": "acme/widgets",
                "repo_id": repo_id,
                "pr_number": 42,
                "head_branch": "feature/scm-rebind",
                "base_branch": "main",
                "thread_target_id": thread_target_id,
            },
        },
    )
    return operation


def test_drain_pending_publish_operations_marks_success_and_does_not_replay_same_call(
    tmp_path: Path,
) -> None:
    store = PublishJournalStore(tmp_path)
    created, _ = store.create_operation(
        operation_key="notify:thread-1",
        operation_kind="notify_chat",
        payload={"body": "ready"},
        next_attempt_at="2026-03-25T00:00:00Z",
    )

    calls: list[tuple[str, int, str]] = []

    def executor(operation):
        calls.append((operation.operation_id, operation.attempt_count, operation.state))
        return {"delivered": True, "remote_id": "msg-123"}

    processed = drain_pending_publish_operations(
        store,
        executor_registry=PublishExecutorRegistry({"notify_chat": executor}),
        limit=10,
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
    )
    assert [operation.operation_id for operation in processed] == [created.operation_id]
    assert processed[0].state == "succeeded"
    assert processed[0].response == {"delivered": True, "remote_id": "msg-123"}
    assert calls == [(created.operation_id, 1, "running")]

    repeated = drain_pending_publish_operations(
        store,
        executor_registry=PublishExecutorRegistry({"notify_chat": executor}),
        limit=10,
        now_fn=_QueuedClock("2026-03-25T00:01:00Z"),
    )
    assert repeated == []
    assert calls == [(created.operation_id, 1, "running")]

    attempts = _attempt_rows(tmp_path, created.operation_id)
    assert len(attempts) == 1
    assert attempts[0]["state"] == "succeeded"
    assert json.loads(str(attempts[0]["response_json"])) == {
        "delivered": True,
        "remote_id": "msg-123",
    }


def test_process_now_applies_bounded_retry_schedule_for_generic_failures(
    tmp_path: Path,
) -> None:
    store = PublishJournalStore(tmp_path)
    created, _ = store.create_operation(
        operation_key="comment:pr-1",
        operation_kind="post_pr_comment",
        payload={"body": "hello"},
        next_attempt_at="2026-03-25T00:00:00Z",
    )

    call_count = 0

    def failing_executor(_operation):
        nonlocal call_count
        call_count += 1
        raise RuntimeError("temporary outage")

    processor = PublishOperationProcessor(
        store,
        executors={"post_pr_comment": failing_executor},
        now_fn=_QueuedClock(
            "2026-03-25T00:00:00Z",
            "2026-03-25T00:00:00Z",
            "2026-03-25T00:00:30Z",
            "2026-03-25T00:05:30Z",
        ),
        mutation_policy_config=_ALLOW_PR_COMMENT_POLICY,
    )

    first = processor.process_now(limit=10)
    assert call_count == 1
    assert [operation.operation_id for operation in first] == [created.operation_id]
    assert first[0].state == "pending"
    assert first[0].attempt_count == 1
    assert first[0].next_attempt_at == "2026-03-25T00:00:00Z"

    second = processor.process_now(limit=10)
    assert call_count == 2
    assert second[0].state == "pending"
    assert second[0].attempt_count == 2
    assert second[0].next_attempt_at == "2026-03-25T00:00:30Z"

    third = processor.process_now(limit=10)
    assert call_count == 3
    assert third[0].state == "pending"
    assert third[0].attempt_count == 3
    assert third[0].next_attempt_at == "2026-03-25T00:05:30Z"

    fourth = processor.process_now(limit=10)
    assert call_count == 4
    assert fourth[0].state == "failed"
    assert fourth[0].attempt_count == 4
    assert fourth[0].next_attempt_at is None
    assert fourth[0].last_error_text == "RuntimeError: temporary outage"

    attempts = _attempt_rows(tmp_path, created.operation_id)
    assert len(attempts) == 4
    assert [attempt["state"] for attempt in attempts] == [
        "failed",
        "failed",
        "failed",
        "failed",
    ]


def test_process_now_marks_terminal_failure_without_retry(
    tmp_path: Path,
) -> None:
    store = PublishJournalStore(tmp_path)
    created, _ = store.create_operation(
        operation_key="comment:pr-terminal",
        operation_kind="post_pr_comment",
        payload={"body": "bad request"},
        next_attempt_at="2026-03-25T00:00:00Z",
    )

    call_count = 0

    def terminal_executor(_operation):
        nonlocal call_count
        call_count += 1
        raise TerminalPublishError("permanent rejection")

    processor = PublishOperationProcessor(
        store,
        executors={"post_pr_comment": terminal_executor},
        now_fn=_QueuedClock("2026-03-25T00:00:00Z", "2026-03-25T00:01:00Z"),
        mutation_policy_config=_ALLOW_PR_COMMENT_POLICY,
    )

    processed = processor.process_now(limit=10)
    assert call_count == 1
    assert [operation.operation_id for operation in processed] == [created.operation_id]
    assert processed[0].state == "failed"
    assert processed[0].next_attempt_at is None
    assert processed[0].last_error_text == "TerminalPublishError: permanent rejection"

    repeated = processor.process_now(limit=10)
    assert repeated == []
    assert call_count == 1


def test_drain_pending_publish_operations_marks_terminal_failure_when_journal_completion_fails(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    store = PublishJournalStore(tmp_path)
    created, _ = store.create_operation(
        operation_key="notify:journal-completion-failure",
        operation_kind="notify_chat",
        payload={"body": "ready"},
        next_attempt_at="2026-03-25T00:00:00Z",
    )
    original_mark_succeeded = store.mark_succeeded

    def _fail_mark_succeeded(
        operation_id: str, *, response: dict[str, object]
    ) -> PublishOperation | None:
        _ = operation_id, response
        raise sqlite3.OperationalError("database is locked")

    monkeypatch.setattr(store, "mark_succeeded", _fail_mark_succeeded)

    processed = drain_pending_publish_operations(
        store,
        executor_registry=PublishExecutorRegistry(
            {"notify_chat": lambda _operation: {"delivered": True}}
        ),
        limit=10,
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
    )

    assert [operation.operation_id for operation in processed] == [created.operation_id]
    assert processed[0].state == "failed"
    assert processed[0].next_attempt_at is None
    assert processed[0].last_error_text is not None
    assert "journal completion failed" in processed[0].last_error_text

    monkeypatch.setattr(store, "mark_succeeded", original_mark_succeeded)
    stored = store.list_operations(limit=10)
    assert len(stored) == 1
    assert stored[0].operation_id == created.operation_id
    assert stored[0].state == "failed"
    assert stored[0].next_attempt_at is None
    assert stored[0].last_error_text is not None
    assert "journal completion failed" in stored[0].last_error_text


def test_drain_pending_publish_operations_skips_operation_when_mark_running_fails() -> (
    None
):
    operation = PublishOperation(
        operation_id="op-1",
        operation_key="notify:op-1",
        operation_kind="notify_chat",
        state="pending",
        payload={"body": "ready"},
        response={},
        created_at="2026-03-25T00:00:00Z",
        updated_at="2026-03-25T00:00:00Z",
        next_attempt_at="2026-03-25T00:00:00Z",
        attempt_count=1,
    )

    class _FakeJournal:
        def claim_pending_operations(self, *, limit: int, now_timestamp: str):
            assert limit == 10
            assert now_timestamp == "2026-03-25T00:00:00Z"
            return [operation]

        def mark_running(self, operation_id: str):
            assert operation_id == "op-1"
            return None

    executor_calls: list[str] = []

    def executor(_operation):
        executor_calls.append("called")
        return {"delivered": True}

    processed = drain_pending_publish_operations(
        _FakeJournal(),
        executor_registry=PublishExecutorRegistry({"notify_chat": executor}),
        limit=10,
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
    )

    assert processed == []
    assert executor_calls == []


def test_process_now_denies_post_pr_comment_without_github_side_effect(
    tmp_path: Path,
) -> None:
    store = PublishJournalStore(tmp_path)
    created, _ = store.create_operation(
        operation_key="comment:pr-denied",
        operation_kind="post_pr_comment",
        payload={
            "repo_slug": "acme/widgets",
            "pr_number": 17,
            "body": "Automation noted a failing check.",
        },
        next_attempt_at="2026-03-25T00:00:00Z",
    )

    service_roots: list[Path] = []

    class _FakeGitHubService:
        def repo_info(self) -> RepoInfo:
            return RepoInfo(
                name_with_owner="acme/widgets",
                url="https://github.com/acme/widgets",
                default_branch="main",
            )

        def create_issue_comment(
            self, *, owner: str, repo: str, number: int, body: str, cwd=None
        ) -> dict[str, object]:
            raise AssertionError("GitHub side effect should be blocked by policy")

    def _factory(repo_root: Path, raw_config=None) -> _FakeGitHubService:
        _ = raw_config
        service_roots.append(repo_root)
        return _FakeGitHubService()

    processor = PublishOperationProcessor(
        store,
        executors={
            "post_pr_comment": build_post_pr_comment_executor(
                repo_root=tmp_path,
                github_service_factory=_factory,
            )
        },
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
    )

    processed = processor.process_now(limit=10)
    assert [operation.operation_id for operation in processed] == [created.operation_id]
    assert processed[0].state == "failed"
    assert processed[0].next_attempt_at is None
    assert processed[0].last_error_text is not None
    assert "PolicyDeniedPublishError" in processed[0].last_error_text
    assert "decision 'deny'" in processed[0].last_error_text
    assert service_roots == []

    attempts = _attempt_rows(tmp_path, created.operation_id)
    assert len(attempts) == 1
    assert attempts[0]["state"] == "failed"
    assert "PolicyDeniedPublishError" in str(attempts[0]["error_text"])


def test_process_now_allows_post_pr_comment_when_policy_allows(
    tmp_path: Path,
) -> None:
    store = PublishJournalStore(tmp_path)
    created, _ = store.create_operation(
        operation_key="comment:pr-allowed",
        operation_kind="post_pr_comment",
        payload={"body": "hello"},
        next_attempt_at="2026-03-25T00:00:00Z",
    )

    calls: list[tuple[str, int, str]] = []

    def executor(operation):
        calls.append((operation.operation_id, operation.attempt_count, operation.state))
        return {"delivered": True}

    processor = PublishOperationProcessor(
        store,
        executors={"post_pr_comment": executor},
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
        mutation_policy_config=_ALLOW_PR_COMMENT_POLICY,
    )

    processed = processor.process_now(limit=10)
    assert [operation.operation_id for operation in processed] == [created.operation_id]
    assert processed[0].state == "succeeded"
    assert processed[0].response == {"delivered": True}
    assert calls == [(created.operation_id, 1, "running")]


def test_process_now_allows_pr_review_comment_reaction_when_policy_allows(
    tmp_path: Path,
) -> None:
    store = PublishJournalStore(tmp_path)
    created, _ = store.create_operation(
        operation_key="reaction:review-comment-allowed",
        operation_kind="react_pr_review_comment",
        payload={
            "repo_slug": "acme/widgets",
            "comment_id": "314",
            "content": "eyes",
        },
        next_attempt_at="2026-03-25T00:00:00Z",
    )
    service_roots: list[Path] = []
    calls: list[tuple[str, int, str, int, str]] = []

    class _FakeGitHubService:
        def repo_info(self) -> RepoInfo:
            return RepoInfo(
                name_with_owner="acme/widgets",
                url="https://github.com/acme/widgets",
                default_branch="main",
            )

        def create_issue_comment(
            self, *, owner: str, repo: str, number: int, body: str, cwd=None
        ) -> dict[str, object]:
            raise AssertionError("Issue comment path should not be used")

        def create_pull_request_review_comment_reaction(
            self,
            *,
            owner: str,
            repo: str,
            comment_id: int,
            content: str,
            cwd=None,
        ) -> dict[str, object]:
            calls.append((owner, repo, str(cwd), comment_id, content))
            return {
                "id": 88,
                "content": content,
                "url": "https://api.github.com/reactions/88",
            }

    def _factory(repo_root: Path, raw_config=None) -> _FakeGitHubService:
        _ = raw_config
        service_roots.append(repo_root)
        return _FakeGitHubService()

    processor = PublishOperationProcessor(
        store,
        executors={
            "react_pr_review_comment": build_react_pr_review_comment_executor(
                repo_root=tmp_path,
                raw_config=_ALLOW_REVIEW_COMMENT_REACTION_POLICY,
                github_service_factory=_factory,
            )
        },
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
    )

    processed = processor.process_now(limit=10)
    assert [operation.operation_id for operation in processed] == [created.operation_id]
    assert processed[0].state == "succeeded"
    assert processed[0].response == {
        "repo_slug": "acme/widgets",
        "comment_id": 314,
        "content": "eyes",
        "reaction_id": 88,
        "url": "https://api.github.com/reactions/88",
    }
    assert service_roots == [tmp_path]
    assert calls == [("acme", "widgets", str(tmp_path), 314, "eyes")]


def test_process_now_replays_pending_operation_after_processor_restart(
    tmp_path: Path,
) -> None:
    first_store = PublishJournalStore(tmp_path)
    created, _ = first_store.create_operation(
        operation_key="enqueue:thread-1",
        operation_kind="enqueue_managed_turn",
        payload={"thread_target_id": "thread-1"},
        next_attempt_at="2026-03-25T00:00:00Z",
    )

    def first_executor(_operation):
        raise RuntimeError("transient failure")

    first_processor = PublishOperationProcessor(
        first_store,
        executors={"enqueue_managed_turn": first_executor},
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
    )
    first_result = first_processor.process_now(limit=10)
    assert first_result[0].state == "pending"
    assert first_result[0].attempt_count == 1
    assert first_result[0].next_attempt_at == "2026-03-25T00:00:00Z"

    second_store = PublishJournalStore(tmp_path)

    def second_executor(operation):
        return {"queued": True, "operation_id": operation.operation_id}

    second_processor = PublishOperationProcessor(
        second_store,
        executors={"enqueue_managed_turn": second_executor},
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
    )
    second_result = second_processor.process_now(limit=10)
    assert [operation.operation_id for operation in second_result] == [
        created.operation_id
    ]
    assert second_result[0].state == "succeeded"
    assert second_result[0].attempt_count == 2
    assert second_result[0].response == {
        "queued": True,
        "operation_id": created.operation_id,
    }

    attempts = _attempt_rows(tmp_path, created.operation_id)
    assert len(attempts) == 2
    assert [attempt["state"] for attempt in attempts] == ["failed", "succeeded"]


def test_enqueue_managed_turn_executor_reuses_existing_execution_for_same_operation(
    tmp_path: Path,
) -> None:
    hub_root, workspace_root, repo_id = _publish_hub(tmp_path)
    thread_store = PmaThreadStore(hub_root)
    thread = thread_store.create_thread("codex", workspace_root, repo_id=repo_id)
    journal = PublishJournalStore(hub_root)
    operation, _ = journal.create_operation(
        operation_key=f"enqueue:{thread['managed_thread_id']}:ci-failure",
        operation_kind="enqueue_managed_turn",
        payload={
            "thread_target_id": thread["managed_thread_id"],
            "message_text": "Investigate the failing check.",
            "request_kind": "review",
        },
    )

    executor = build_enqueue_managed_turn_executor(
        hub_root=hub_root, thread_store=thread_store
    )
    first = executor(operation)
    second = executor(operation)

    assert first["managed_turn_id"] == second["managed_turn_id"]
    assert first["status"] == "running"
    assert first["queued"] is False
    assert first["deduped"] is False
    assert second["deduped"] is True

    turns = thread_store.list_turns(thread["managed_thread_id"])
    assert len(turns) == 1
    assert turns[0]["request_kind"] == "review"
    assert turns[0]["client_turn_id"] == first["client_request_id"]


@pytest.mark.parametrize(
    ("turn_status", "expected_runtime_status"),
    [("ok", "completed"), ("interrupted", "interrupted")],
)
def test_enqueue_managed_turn_executor_reuses_reusable_scm_thread_statuses(
    tmp_path: Path,
    caplog: pytest.LogCaptureFixture,
    turn_status: str,
    expected_runtime_status: str,
) -> None:
    hub_root, workspace_root, repo_id = _publish_hub(tmp_path)
    thread_store = PmaThreadStore(hub_root)
    thread = thread_store.create_thread(
        "codex",
        workspace_root,
        repo_id=repo_id,
        metadata={"head_branch": "feature/scm-rebind"},
    )
    first_turn = thread_store.create_turn(
        thread["managed_thread_id"], prompt="existing work"
    )
    if turn_status == "ok":
        assert thread_store.mark_turn_finished(
            first_turn["managed_turn_id"], status="ok"
        )
    else:
        assert thread_store.mark_turn_interrupted(first_turn["managed_turn_id"])

    binding = PrBindingStore(hub_root).upsert_binding(
        provider="github",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        pr_state="open",
        head_branch="feature/scm-rebind",
        base_branch="main",
        thread_target_id=thread["managed_thread_id"],
    )
    operation = _create_scm_enqueue_operation(
        journal=PublishJournalStore(hub_root),
        thread_target_id=thread["managed_thread_id"],
        binding_id=binding.binding_id,
        repo_id=repo_id,
        operation_key=f"enqueue:scm:{expected_runtime_status}",
    )

    with caplog.at_level(
        logging.INFO, logger="codex_autorunner.core.publish_operation_executors"
    ):
        result = build_enqueue_managed_turn_executor(
            hub_root=hub_root, thread_store=thread_store
        )(operation)

    assert result["thread_target_id"] == thread["managed_thread_id"]
    assert result["queued"] is False
    turns = thread_store.list_turns(thread["managed_thread_id"], limit=10)
    assert len(turns) == 2
    assert turns[0]["managed_turn_id"] == result["managed_turn_id"]
    assert turns[0]["status"] == "running"
    assert any(
        "scm.enqueue_managed_turn.reusing_thread" in message
        and f"normalized_status={expected_runtime_status}" in message
        for message in caplog.messages
    )


def test_enqueue_managed_turn_executor_queues_on_running_scm_thread(
    tmp_path: Path,
    caplog: pytest.LogCaptureFixture,
) -> None:
    hub_root, workspace_root, repo_id = _publish_hub(tmp_path)
    thread_store = PmaThreadStore(hub_root)
    thread = thread_store.create_thread(
        "codex",
        workspace_root,
        repo_id=repo_id,
        metadata={"head_branch": "feature/scm-rebind"},
    )
    existing_turn = thread_store.create_turn(
        thread["managed_thread_id"], prompt="already running"
    )
    binding = PrBindingStore(hub_root).upsert_binding(
        provider="github",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        pr_state="open",
        head_branch="feature/scm-rebind",
        base_branch="main",
        thread_target_id=thread["managed_thread_id"],
    )
    operation = _create_scm_enqueue_operation(
        journal=PublishJournalStore(hub_root),
        thread_target_id=thread["managed_thread_id"],
        binding_id=binding.binding_id,
        repo_id=repo_id,
        operation_key="enqueue:scm:running-thread",
    )

    with caplog.at_level(
        logging.INFO, logger="codex_autorunner.core.publish_operation_executors"
    ):
        result = build_enqueue_managed_turn_executor(
            hub_root=hub_root, thread_store=thread_store
        )(operation)

    assert result["thread_target_id"] == thread["managed_thread_id"]
    assert result["queued"] is True
    turns = thread_store.list_turns(thread["managed_thread_id"], limit=10)
    assert len(turns) == 2
    assert {turn["managed_turn_id"] for turn in turns} == {
        existing_turn["managed_turn_id"],
        result["managed_turn_id"],
    }
    queued = [
        turn for turn in turns if turn["managed_turn_id"] == result["managed_turn_id"]
    ][0]
    assert queued["status"] == "queued"
    assert any(
        "scm.enqueue_managed_turn.reusing_thread" in message
        and "normalized_status=running" in message
        for message in caplog.messages
    )


def test_enqueue_managed_turn_executor_merges_into_existing_queued_scm_turn(
    tmp_path: Path,
) -> None:
    hub_root, workspace_root, repo_id = _publish_hub(tmp_path)
    thread_store = PmaThreadStore(hub_root)
    thread = thread_store.create_thread(
        "codex",
        workspace_root,
        repo_id=repo_id,
        metadata={"head_branch": "feature/scm-rebind"},
    )
    running_turn = thread_store.create_turn(
        thread["managed_thread_id"], prompt="already running"
    )
    binding = PrBindingStore(hub_root).upsert_binding(
        provider="github",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        pr_state="open",
        head_branch="feature/scm-rebind",
        base_branch="main",
        thread_target_id=thread["managed_thread_id"],
    )
    journal = PublishJournalStore(hub_root)
    first = _create_scm_enqueue_operation(
        journal=journal,
        thread_target_id=thread["managed_thread_id"],
        binding_id=binding.binding_id,
        repo_id=repo_id,
        operation_key="enqueue:scm:queued-merge-1",
    )
    first = replace(
        first,
        payload={
            **first.payload,
            "request": {
                **first.payload["request"],
                "message_text": "New PR review feedback arrived on acme/widgets#42.",
                "metadata": {
                    **first.payload["request"]["metadata"],
                    "scm_feedback_bundle": {
                        "version": 1,
                        "subject": "acme/widgets#42",
                        "binding_id": binding.binding_id,
                        "thread_target_id": thread["managed_thread_id"],
                        "repo_slug": "acme/widgets",
                        "pr_number": 42,
                        "opened_at": "2026-03-26T00:00:01Z",
                        "last_event_at": "2026-03-26T00:00:01Z",
                        "batch_mode": "general",
                        "items": [
                            {
                                "event_id": "github:event-review-comment-1",
                                "event_type": "pull_request_review_comment",
                                "reaction_kind": "review_comment",
                                "message_text": "New PR review feedback arrived on acme/widgets#42.",
                                "received_at": "2026-03-26T00:00:01Z",
                            }
                        ],
                    },
                },
            },
        },
    )
    second = _create_scm_enqueue_operation(
        journal=journal,
        thread_target_id=thread["managed_thread_id"],
        binding_id=binding.binding_id,
        repo_id=repo_id,
        operation_key="enqueue:scm:queued-merge-2",
    )
    second = replace(
        second,
        payload={
            **second.payload,
            "request": {
                **second.payload["request"],
                "message_text": "CI failed for acme/widgets#42: chat-apps (failure). Inspect the failing check and push a fix.",
                "metadata": {
                    **second.payload["request"]["metadata"],
                    "scm_feedback_bundle": {
                        "version": 1,
                        "subject": "acme/widgets#42",
                        "binding_id": binding.binding_id,
                        "thread_target_id": thread["managed_thread_id"],
                        "repo_slug": "acme/widgets",
                        "pr_number": 42,
                        "opened_at": "2026-03-26T00:00:15Z",
                        "last_event_at": "2026-03-26T00:00:15Z",
                        "batch_mode": "ci_failed",
                        "ci_head_sha": "abc123",
                        "items": [
                            {
                                "event_id": "github:event-ci-1",
                                "event_type": "check_run",
                                "reaction_kind": "ci_failed",
                                "message_text": "CI failed for acme/widgets#42: chat-apps (failure). Inspect the failing check and push a fix.",
                                "received_at": "2026-03-26T00:00:15Z",
                                "check_name": "chat-apps",
                                "conclusion": "failure",
                                "head_sha": "abc123",
                            }
                        ],
                    },
                },
            },
        },
    )

    executor = build_enqueue_managed_turn_executor(
        hub_root=hub_root, thread_store=thread_store
    )
    first_result = executor(first)
    second_result = executor(second)

    assert first_result["queued"] is True
    assert second_result["queued"] is True
    assert second_result["deduped"] is True
    assert first_result["managed_turn_id"] == second_result["managed_turn_id"]
    assert first_result["client_request_id"] == second_result["client_request_id"]

    turns = thread_store.list_turns(thread["managed_thread_id"], limit=10)
    assert len(turns) == 2
    assert {turn["managed_turn_id"] for turn in turns} == {
        running_turn["managed_turn_id"],
        first_result["managed_turn_id"],
    }
    queued_turn = [
        turn
        for turn in turns
        if turn["managed_turn_id"] == first_result["managed_turn_id"]
    ][0]
    assert queued_turn["prompt"].startswith(
        "Multiple SCM updates arrived for acme/widgets#42:"
    )
    assert "New PR review feedback arrived on acme/widgets#42." in queued_turn["prompt"]
    assert (
        "CI failed for acme/widgets#42: chat-apps (failure). Inspect the failing check and push a fix."
        in queued_turn["prompt"]
    )
    queued_payload = thread_store.get_queued_turn_queue_payload(
        thread["managed_thread_id"],
        queued_turn["managed_turn_id"],
    )
    assert queued_payload is not None
    assert queued_payload["request"]["message_text"] == queued_turn["prompt"]


def test_enqueue_managed_turn_executor_rebinds_instead_of_merging_stale_archived_queue(
    tmp_path: Path,
) -> None:
    hub_root, workspace_root, repo_id = _publish_hub(tmp_path)
    thread_store = PmaThreadStore(hub_root)
    archived_thread = thread_store.create_thread(
        "codex",
        workspace_root,
        repo_id=repo_id,
        metadata={"head_branch": "feature/scm-rebind"},
    )
    thread_store.create_turn(archived_thread["managed_thread_id"], prompt="running")
    thread_store.create_turn(
        archived_thread["managed_thread_id"],
        prompt="queued stale scm turn",
        busy_policy="queue",
    )
    thread_store.archive_thread(archived_thread["managed_thread_id"])

    binding = PrBindingStore(hub_root).upsert_binding(
        provider="github",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        pr_state="open",
        head_branch="feature/scm-rebind",
        base_branch="main",
        thread_target_id=archived_thread["managed_thread_id"],
    )
    event = ScmEventStore(hub_root).record_event(
        provider="github",
        event_type="check_run",
        event_id="github:event-archived-ci",
        occurred_at="2026-03-25T00:00:00Z",
        received_at="2026-03-25T00:00:01Z",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        payload={
            "action": "completed",
            "status": "completed",
            "conclusion": "failure",
            "name": "chat-apps",
            "head_sha": "abc123",
        },
    )
    operation = _create_scm_enqueue_operation(
        journal=PublishJournalStore(hub_root),
        thread_target_id=archived_thread["managed_thread_id"],
        binding_id=binding.binding_id,
        repo_id=repo_id,
        operation_key="enqueue:scm:archived-queued-merge",
    )
    operation = replace(
        operation,
        payload={
            **operation.payload,
            "request": {
                **operation.payload["request"],
                "message_text": "CI failed for acme/widgets#42: chat-apps (failure). Inspect the failing check and push a fix.",
                "metadata": {
                    "scm": {
                        **operation.payload["request"]["metadata"]["scm"],
                        "event_id": event.event_id,
                    },
                    "scm_feedback_bundle": {
                        "version": 1,
                        "subject": "acme/widgets#42",
                        "binding_id": binding.binding_id,
                        "thread_target_id": archived_thread["managed_thread_id"],
                        "repo_slug": "acme/widgets",
                        "pr_number": 42,
                        "opened_at": "2026-03-25T00:00:01Z",
                        "last_event_at": "2026-03-25T00:00:01Z",
                        "batch_mode": "ci_failed",
                        "ci_head_sha": "abc123",
                        "items": [
                            {
                                "event_id": event.event_id,
                                "event_type": "check_run",
                                "reaction_kind": "ci_failed",
                                "message_text": "CI failed for acme/widgets#42: chat-apps (failure). Inspect the failing check and push a fix.",
                                "received_at": "2026-03-25T00:00:01Z",
                                "check_name": "chat-apps",
                                "conclusion": "failure",
                                "head_sha": "abc123",
                            }
                        ],
                    },
                },
            },
            "scm_reaction": {
                **operation.payload["scm_reaction"],
                "event_id": event.event_id,
            },
        },
    )

    result = build_enqueue_managed_turn_executor(
        hub_root=hub_root, thread_store=thread_store
    )(operation)

    assert result["thread_target_id"] != archived_thread["managed_thread_id"]
    rebound_binding = PrBindingStore(hub_root).get_binding_by_pr(
        provider="github",
        repo_slug="acme/widgets",
        pr_number=42,
    )
    assert rebound_binding is not None
    assert rebound_binding.thread_target_id == result["thread_target_id"]


def test_enqueue_managed_turn_executor_rebinds_archived_scm_thread_with_bootstrap_prompt(
    tmp_path: Path,
    caplog: pytest.LogCaptureFixture,
) -> None:
    hub_root, workspace_root, repo_id = _publish_hub(tmp_path)
    thread_store = PmaThreadStore(hub_root)
    archived_thread = thread_store.create_thread(
        "codex",
        workspace_root,
        repo_id=repo_id,
        name="Original PR thread",
        metadata={"head_branch": "feature/scm-rebind"},
    )
    thread_store.archive_thread(archived_thread["managed_thread_id"])

    binding = PrBindingStore(hub_root).upsert_binding(
        provider="github",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        pr_state="open",
        head_branch="feature/scm-rebind",
        base_branch="main",
        thread_target_id=archived_thread["managed_thread_id"],
    )
    event = ScmEventStore(hub_root).record_event(
        provider="github",
        event_type="pull_request_review_comment",
        event_id="github:event-rebind",
        occurred_at="2026-03-25T00:00:00Z",
        received_at="2026-03-25T00:00:01Z",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        payload={
            "action": "created",
            "comment_id": "314",
            "author_login": "reviewer",
            "body": "Please cover the archived-thread fallback.",
            "path": "src/codex_autorunner/core/scm_automation_service.py",
            "line": 371,
        },
    )
    operation = _create_scm_enqueue_operation(
        journal=PublishJournalStore(hub_root),
        thread_target_id=archived_thread["managed_thread_id"],
        binding_id=binding.binding_id,
        repo_id=repo_id,
        operation_key="enqueue:scm:archived-thread",
    )
    operation = replace(
        operation,
        payload={
            **operation.payload,
            "request": {
                **operation.payload["request"],
                "metadata": {
                    "scm": {
                        **operation.payload["request"]["metadata"]["scm"],
                        "event_id": event.event_id,
                    }
                },
            },
            "scm_reaction": {
                **operation.payload["scm_reaction"],
                "event_id": event.event_id,
            },
        },
    )

    with caplog.at_level(
        logging.INFO, logger="codex_autorunner.core.publish_operation_executors"
    ):
        result = build_enqueue_managed_turn_executor(
            hub_root=hub_root, thread_store=thread_store
        )(operation)

    assert result["thread_target_id"] != archived_thread["managed_thread_id"]
    assert (
        result["rebound_from_thread_target_id"] == archived_thread["managed_thread_id"]
    )

    rebound_binding = PrBindingStore(hub_root).get_binding_by_pr(
        provider="github",
        repo_slug="acme/widgets",
        pr_number=42,
    )
    assert rebound_binding is not None
    assert rebound_binding.thread_target_id == result["thread_target_id"]

    turns = thread_store.list_turns(result["thread_target_id"])
    assert len(turns) == 1
    queued = turns[0]
    assert "Bootstrap a fresh SCM PR follow-up session" in queued["prompt"]
    assert "Target PR: acme/widgets#42" in queued["prompt"]
    assert "Start with the latest review comment 314" in queued["prompt"]
    assert "gh pr view 42 --repo acme/widgets --comments" in queued["prompt"]
    assert "push them to the PR branch" in queued["prompt"]

    replacement_thread = thread_store.get_thread(result["thread_target_id"])
    assert replacement_thread is not None
    assert replacement_thread["metadata"]["pr_number"] == 42
    assert replacement_thread["metadata"]["pr_url"] == (
        "https://github.com/acme/widgets/pull/42"
    )
    assert replacement_thread["metadata"]["head_branch"] == "feature/scm-rebind"
    assert any(
        "scm.enqueue_managed_turn.rebinding_thread" in message
        and f"previous_thread_target_id={archived_thread['managed_thread_id']}"
        in message
        and "status=archived" in message
        for message in caplog.messages
    )
    assert any(
        "scm.enqueue_managed_turn.rebound_thread" in message
        and f"previous_thread_target_id={archived_thread['managed_thread_id']}"
        in message
        and f"thread_target_id={result['thread_target_id']}" in message
        for message in caplog.messages
    )


def test_enqueue_managed_turn_executor_dedupes_retry_after_scm_rebind_to_new_thread(
    tmp_path: Path,
) -> None:
    """If the PR binding moves to a replacement thread, retries must still dedupe."""
    hub_root, workspace_root, repo_id = _publish_hub(tmp_path)
    thread_store = PmaThreadStore(hub_root)
    archived_thread = thread_store.create_thread(
        "codex",
        workspace_root,
        repo_id=repo_id,
        name="Original PR thread",
    )
    thread_store.archive_thread(archived_thread["managed_thread_id"])

    binding = PrBindingStore(hub_root).upsert_binding(
        provider="github",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        pr_state="open",
        head_branch="feature/scm-rebind",
        base_branch="main",
        thread_target_id=archived_thread["managed_thread_id"],
    )
    event = ScmEventStore(hub_root).record_event(
        provider="github",
        event_type="pull_request_review_comment",
        event_id="github:event-rebind-dedupe",
        occurred_at="2026-03-25T00:00:00Z",
        received_at="2026-03-25T00:00:01Z",
        repo_slug="acme/widgets",
        repo_id=repo_id,
        pr_number=42,
        payload={
            "action": "created",
            "comment_id": "314",
            "author_login": "reviewer",
            "body": "Dedupe after rebind.",
            "path": "src/example.py",
            "line": 1,
        },
    )
    journal = PublishJournalStore(hub_root)
    operation, _ = journal.create_operation(
        operation_key="enqueue:scm:archived-thread-retry-dedupe",
        operation_kind="enqueue_managed_turn",
        payload={
            "thread_target_id": archived_thread["managed_thread_id"],
            "request": {
                "kind": "message",
                "message_text": "First attempt message.",
                "metadata": {
                    "scm": {
                        "binding_id": binding.binding_id,
                        "event_id": event.event_id,
                        "provider": "github",
                        "repo_slug": "acme/widgets",
                        "repo_id": repo_id,
                        "pr_number": 42,
                    }
                },
            },
            "scm_reaction": {
                "binding_id": binding.binding_id,
                "event_id": event.event_id,
                "provider": "github",
                "reaction_kind": "review_comment",
                "repo_slug": "acme/widgets",
                "repo_id": repo_id,
                "pr_number": 42,
                "thread_target_id": archived_thread["managed_thread_id"],
            },
        },
    )

    executor = build_enqueue_managed_turn_executor(
        hub_root=hub_root, thread_store=thread_store
    )
    first = executor(operation)
    second = executor(operation)

    assert first["deduped"] is False
    assert second["deduped"] is True
    assert first["managed_turn_id"] == second["managed_turn_id"]
    assert first["thread_target_id"] == second["thread_target_id"]

    rebound_id = first["thread_target_id"]
    assert rebound_id != archived_thread["managed_thread_id"]
    turns = thread_store.list_turns(rebound_id)
    assert len(turns) == 1


def test_process_now_runs_first_publish_operation_types(
    tmp_path: Path,
) -> None:
    hub_root, workspace_root, repo_id = _publish_hub(tmp_path)
    thread_store = PmaThreadStore(hub_root)
    thread = thread_store.create_thread("codex", workspace_root, repo_id=repo_id)

    async def _seed_binding() -> None:
        store = DiscordStateStore(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3"
        )
        try:
            await store.upsert_binding(
                channel_id="repo-discord",
                guild_id="guild-1",
                workspace_path=str(workspace_root),
                repo_id=repo_id,
            )
        finally:
            await store.close()

    asyncio.run(_seed_binding())

    journal = PublishJournalStore(hub_root)
    enqueue_operation, _ = journal.create_operation(
        operation_key=f"enqueue:{thread['managed_thread_id']}:check-failed",
        operation_kind="enqueue_managed_turn",
        payload={
            "thread_target_id": thread["managed_thread_id"],
            "message_text": "A check failed. Triage the failure.",
        },
        next_attempt_at="2026-03-25T00:00:00Z",
    )
    notify_operation, _ = journal.create_operation(
        operation_key=f"notify:{thread['managed_thread_id']}:check-failed",
        operation_kind="notify_chat",
        payload={
            "thread_target_id": thread["managed_thread_id"],
            "message": "CI failed on the bound repo.",
        },
        next_attempt_at="2026-03-25T00:00:00Z",
    )
    comment_operation, _ = journal.create_operation(
        operation_key="comment:acme/widgets:17:check-failed",
        operation_kind="post_pr_comment",
        payload={
            "repo_slug": "acme/widgets",
            "pr_number": 17,
            "body": "Automation noted a failing check.",
        },
        next_attempt_at="2026-03-25T00:00:00Z",
    )

    github_calls: list[dict[str, object]] = []

    class _FakeGitHubService:
        def __init__(self, repo_root: Path, raw_config=None) -> None:
            assert repo_root == workspace_root
            _ = raw_config

        def repo_info(self) -> RepoInfo:
            return RepoInfo(
                name_with_owner="acme/widgets",
                url="https://github.com/acme/widgets",
                default_branch="main",
            )

        def create_issue_comment(
            self, *, owner: str, repo: str, number: int, body: str, cwd=None
        ) -> dict[str, object]:
            github_calls.append(
                {
                    "owner": owner,
                    "repo": repo,
                    "number": number,
                    "body": body,
                    "cwd": cwd,
                }
            )
            return {
                "id": 321,
                "html_url": "https://github.com/acme/widgets/pull/17#issuecomment-321",
            }

    processor = PublishOperationProcessor(
        journal,
        executors=PublishExecutorRegistry(
            {
                "enqueue_managed_turn": build_enqueue_managed_turn_executor(
                    hub_root=hub_root, thread_store=thread_store
                ),
                "notify_chat": build_notify_chat_executor(
                    hub_root=hub_root, thread_store=thread_store
                ),
                "post_pr_comment": build_post_pr_comment_executor(
                    repo_root=workspace_root,
                    raw_config=_ALLOW_PR_COMMENT_POLICY,
                    github_service_factory=_FakeGitHubService,
                ),
            }
        ),
        now_fn=_QueuedClock("2026-03-25T00:00:00Z"),
    )

    processed = processor.process_now(limit=10)
    processed_by_id = {operation.operation_id: operation for operation in processed}
    assert set(processed_by_id) == {
        enqueue_operation.operation_id,
        notify_operation.operation_id,
        comment_operation.operation_id,
    }
    assert all(operation.state == "succeeded" for operation in processed)

    enqueue_result = processed_by_id[enqueue_operation.operation_id].response
    assert enqueue_result["thread_target_id"] == thread["managed_thread_id"]
    assert enqueue_result["queued"] is False
    assert enqueue_result["status"] == "running"

    notify_result = processed_by_id[notify_operation.operation_id].response
    assert notify_result == {
        "delivery": "auto",
        "repo_id": repo_id,
        "route": "bound",
        "targets": 1,
        "published": 1,
    }

    comment_result = processed_by_id[comment_operation.operation_id].response
    assert comment_result == {
        "repo_slug": "acme/widgets",
        "pr_number": 17,
        "comment_id": 321,
        "url": "https://github.com/acme/widgets/pull/17#issuecomment-321",
    }

    turns = thread_store.list_turns(thread["managed_thread_id"])
    assert len(turns) == 1
    assert turns[0]["managed_turn_id"] == enqueue_result["managed_turn_id"]

    async def _load_outbox() -> list[object]:
        store = DiscordStateStore(
            hub_root / ".codex-autorunner" / "discord_state.sqlite3"
        )
        try:
            return await store.list_outbox()
        finally:
            await store.close()

    outbox = asyncio.run(_load_outbox())
    assert any(
        record.channel_id == "repo-discord"
        and record.payload_json.get("content") == "CI failed on the bound repo."
        for record in outbox
    )
    assert github_calls == [
        {
            "owner": "acme",
            "repo": "widgets",
            "number": 17,
            "body": "Automation noted a failing check.",
            "cwd": workspace_root,
        }
    ]

    enqueue_attempts = _attempt_rows(hub_root, enqueue_operation.operation_id)
    notify_attempts = _attempt_rows(hub_root, notify_operation.operation_id)
    comment_attempts = _attempt_rows(hub_root, comment_operation.operation_id)
    assert enqueue_attempts[0]["state"] == "succeeded"
    assert notify_attempts[0]["state"] == "succeeded"
    assert comment_attempts[0]["state"] == "succeeded"


@pytest.mark.asyncio
async def test_notify_chat_executor_runs_while_event_loop_is_active(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    hub_root, _workspace_root, _repo_id = _publish_hub(tmp_path)
    calls: list[dict[str, object]] = []

    async def _fake_notify_primary_pma_chat_for_repo(
        *,
        hub_root: Path,
        repo_id: str | None,
        message: str,
        correlation_id: str,
    ) -> dict[str, int]:
        calls.append(
            {
                "hub_root": hub_root,
                "repo_id": repo_id,
                "message": message,
            }
        )
        return {"targets": 1, "published": 1}

    monkeypatch.setattr(
        "codex_autorunner.core.publish_operation_executors.notify_primary_pma_chat_for_repo",
        _fake_notify_primary_pma_chat_for_repo,
    )
    executor = build_notify_chat_executor(hub_root=hub_root)
    operation = PublishOperation(
        operation_id="op-async",
        operation_key="notify:async",
        operation_kind="notify_chat",
        state="pending",
        payload={
            "delivery": "primary_pma",
            "message": "ready",
            "repo_id": _repo_id,
        },
        response={},
        created_at="2026-03-25T00:00:00Z",
        updated_at="2026-03-25T00:00:00Z",
        next_attempt_at="2026-03-25T00:00:00Z",
        attempt_count=1,
    )

    result = executor(operation)

    assert result == {
        "delivery": "primary_pma",
        "repo_id": _repo_id,
        "targets": 1,
        "published": 1,
    }
    assert calls == [
        {
            "hub_root": hub_root,
            "repo_id": _repo_id,
            "message": "ready",
        }
    ]
