"""Typed browser render models and helpers."""

from .actions import (
    DemoExecutionResult,
    DemoManifest,
    DemoStep,
    DemoStepReport,
    execute_demo_manifest,
    load_demo_manifest,
)
from .artifacts import (
    ArtifactWriteResult,
    deterministic_artifact_name,
    reserve_artifact_path,
    write_json_artifact,
    write_text_artifact,
)
from .models import (
    DEFAULT_VIEWPORT,
    DEFAULT_VIEWPORT_TEXT,
    RenderTarget,
    TargetMode,
    Viewport,
    parse_viewport,
    resolve_out_dir,
    resolve_output_path,
    select_render_target,
)
from .primitives import ObservePageResult, act_step, capture_artifact, observe_page
from .runtime import (
    BrowserArtifactError,
    BrowserNavigationError,
    BrowserRunResult,
    BrowserRuntime,
    DemoStepError,
    ManifestValidationError,
    build_navigation_url,
)
from .server import (
    BadReadyUrlError,
    BrowserServeConfig,
    BrowserServerSupervisor,
    BrowserServeSession,
    ProcessExitedEarlyError,
    ReadinessTimeoutError,
    ServeModeError,
    parse_env_overrides,
    supervised_server,
)

__all__ = [
    "ArtifactWriteResult",
    "DemoExecutionResult",
    "DemoManifest",
    "DemoStep",
    "DemoStepError",
    "DemoStepReport",
    "ManifestValidationError",
    "BrowserRunResult",
    "BrowserServeConfig",
    "BrowserServeSession",
    "BrowserServerSupervisor",
    "BrowserRuntime",
    "BrowserArtifactError",
    "BrowserNavigationError",
    "ObservePageResult",
    "DEFAULT_VIEWPORT",
    "DEFAULT_VIEWPORT_TEXT",
    "RenderTarget",
    "BadReadyUrlError",
    "ProcessExitedEarlyError",
    "ReadinessTimeoutError",
    "ServeModeError",
    "TargetMode",
    "Viewport",
    "build_navigation_url",
    "deterministic_artifact_name",
    "execute_demo_manifest",
    "load_demo_manifest",
    "act_step",
    "capture_artifact",
    "observe_page",
    "parse_viewport",
    "reserve_artifact_path",
    "resolve_out_dir",
    "resolve_output_path",
    "select_render_target",
    "parse_env_overrides",
    "supervised_server",
    "write_json_artifact",
    "write_text_artifact",
]
